import { FleetVehicle } from './types';

export const FLEET_VEHICLES: FleetVehicle[] = [
  // Tow Trucks (15 total) - Actual fleet vehicles that do the towing
  {
    id: 'truck-001',
    vin: '1FTBW2CM5GKA12345',
    make: 'Ford',
    model: 'F-450 Super Duty',
    year: 2022,
    driver: 'Ethan Carter',
    type: 'Tow Truck',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '4221 Curtis Ave, Baltimore, MD 21226',
    storageLot: 'Curtis Ave Storage Lot',
    zone: 'Balt CO',
    market: 'Maryland',
    shift: 'Day',
    shiftGoal: { current: 8, total: 12 }
  },
  {
    id: 'truck-002',
    vin: '1FTBW2CM5GKA12346',
    make: 'Chevrolet',
    model: 'Silverado 3500HD',
    year: 2021,
    driver: 'Liam Harper',
    type: 'Tow Truck',
    status: 'Active',
    startingPoint: 'Not Fixed',
    location: '751 W Patapsco Ave, Halethorpe, MD 21227',
    storageLot: 'Patapsco Storage Lot',
    zone: 'Balt East',
    market: 'Maryland',
    shift: 'Night',
    shiftGoal: { current: 6, total: 10 }
  },
  {
    id: 'truck-003',
    vin: '1FTBW2CM5GKA12347',
    make: 'Ford',
    model: 'F-550 Super Duty',
    year: 2023,
    driver: 'Maya Patel',
    type: 'Tow Truck',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '4221 Curtis Ave, Baltimore, MD 21226',
    storageLot: 'Curtis Ave Storage Lot',
    zone: 'Balt CO',
    market: 'Maryland',
    shift: 'Day',
    shiftGoal: { current: 10, total: 12 }
  },
  {
    id: 'truck-004',
    vin: 'ZYXWVUT987654321',
    make: 'Ram',
    model: '2500',
    year: 2019,
    driver: 'Noah Kim',
    type: 'Tow Truck',
    status: 'Active',
    startingPoint: 'Not Fixed',
    location: '321 Cedar Ave, Anytown',
    storageLot: 'Lot C, 789 Birch St, Anytown',
    zone: 'East',
    market: 'Local',
    shift: 'Night',
    shiftGoal: { current: 5, total: 10 }
  },
  {
    id: 'truck-005',
    vin: '1111222233334444',
    make: 'Ford',
    model: 'F-350',
    year: 2022,
    driver: 'Emma Rodriguez',
    type: 'Tow Truck',
    status: 'Maintenance',
    maintenanceStatus: 'Brake Service',
    startingPoint: 'Fixed',
    location: '654 Walnut Dr, Anytown',
    storageLot: 'Lot A, 456 Maple Ave, Anytown',
    zone: 'North',
    market: 'Local',
    shift: 'Day',
    shiftGoal: { current: 3, total: 12 }
  },
  {
    id: 'truck-006',
    vin: '5555666677778888',
    make: 'Chevrolet',
    model: 'Silverado 3500',
    year: 2020,
    driver: 'Oliver Chen',
    type: 'Tow Truck',
    status: 'Active',
    startingPoint: 'Not Fixed',
    location: '987 Spruce St, Anytown',
    storageLot: 'Lot B, 101 Pine Ave, Anytown',
    zone: 'South',
    market: 'Regional',
    shift: 'Night',
    shiftGoal: { current: 7, total: 10 }
  },
  {
    id: 'truck-007',
    vin: '9999000011112222',
    make: 'Ford',
    model: 'F-450',
    year: 2023,
    driver: 'Ava Johnson',
    type: 'Tow Truck',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '147 Hickory Ln, Anytown',
    storageLot: 'Lot C, 789 Birch St, Anytown',
    zone: 'East',
    market: 'Local',
    shift: 'Day',
    shiftGoal: { current: 9, total: 15 }
  },
  {
    id: 'truck-008',
    vin: '3333444455556666',
    make: 'Ram',
    model: '3500',
    year: 2021,
    driver: 'William Davis',
    type: 'Tow Truck',
    status: 'Active',
    startingPoint: 'Not Fixed',
    location: '258 Poplar Way, Anytown',
    storageLot: 'Lot A, 456 Maple Ave, Anytown',
    zone: 'North',
    market: 'Local',
    shift: 'Night',
    shiftGoal: { current: 4, total: 12 }
  },
  {
    id: 'truck-009',
    vin: '7777888899990000',
    make: 'Ford',
    model: 'F-250',
    year: 2019,
    driver: 'Sophia Wilson',
    type: 'Tow Truck',
    status: 'Inactive',
    startingPoint: 'Fixed',
    location: '369 Ash Blvd, Anytown',
    storageLot: 'Lot B, 101 Pine Ave, Anytown',
    zone: 'South',
    market: 'Regional',
    shift: 'Day',
    shiftGoal: { current: 1, total: 8 }
  },
  {
    id: 'truck-010',
    vin: '4444555566667777',
    make: 'Chevrolet',
    model: 'Silverado',
    year: 2022,
    driver: 'James Brown',
    type: 'Tow Truck',
    status: 'Active',
    startingPoint: 'Not Fixed',
    location: '741 Dogwood Dr, Anytown',
    storageLot: 'Lot C, 789 Birch St, Anytown',
    zone: 'East',
    market: 'Local',
    shift: 'Night',
    shiftGoal: { current: 11, total: 15 }
  },
  {
    id: 'truck-011',
    vin: '8888999900001111',
    make: 'Ford',
    model: 'F-350',
    year: 2020,
    driver: 'Isabella Garcia',
    type: 'Tow Truck',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '852 Sycamore St, Anytown',
    storageLot: 'Lot A, 456 Maple Ave, Anytown',
    zone: 'North',
    market: 'Local',
    shift: 'Day',
    shiftGoal: { current: 6, total: 12 }
  },
  {
    id: 'truck-012',
    vin: '2222333344445555',
    make: 'Ram',
    model: '2500',
    year: 2021,
    driver: 'Benjamin Miller',
    type: 'Tow Truck',
    status: 'Maintenance',
    maintenanceStatus: 'Oil Change',
    startingPoint: 'Not Fixed',
    location: '963 Magnolia Ave, Anytown',
    storageLot: 'Lot B, 101 Pine Ave, Anytown',
    zone: 'South',
    market: 'Regional',
    shift: 'Night',
    shiftGoal: { current: 2, total: 10 }
  },
  {
    id: 'truck-013',
    vin: '6666777788889999',
    make: 'Ford',
    model: 'F-450',
    year: 2023,
    driver: 'Charlotte Anderson',
    type: 'Tow Truck',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '159 Chestnut Rd, Anytown',
    storageLot: 'Lot C, 789 Birch St, Anytown',
    zone: 'East',
    market: 'Local',
    shift: 'Day',
    shiftGoal: { current: 13, total: 15 }
  },
  {
    id: 'truck-014',
    vin: '0000111122223333',
    make: 'Chevrolet',
    model: 'Silverado 3500',
    year: 2019,
    driver: 'Lucas Martinez',
    type: 'Tow Truck',
    status: 'Active',
    startingPoint: 'Not Fixed',
    location: '357 Locust St, Anytown',
    storageLot: 'Lot A, 456 Maple Ave, Anytown',
    zone: 'North',
    market: 'Local',
    shift: 'Night',
    shiftGoal: { current: 8, total: 12 }
  },
  {
    id: 'truck-015',
    vin: '4444555566667777',
    make: 'Ford',
    model: 'F-250',
    year: 2022,
    driver: 'Amelia Taylor',
    type: 'Tow Truck',
    status: 'Inactive',
    startingPoint: 'Fixed',
    location: '753 Cherry Ln, Anytown',
    storageLot: 'Lot B, 101 Pine Ave, Anytown',
    zone: 'South',
    market: 'Regional',
    shift: 'Day',
    shiftGoal: { current: 0, total: 10 }
  },

  // Spotters (8 total) - Yard trucks/terminal tractors for moving trailers
  {
    id: 'spotter-001',
    vin: 'SPOT001234567890',
    make: 'Ford',
    model: 'F-350 Yard Tractor',
    year: 2021,
    driver: 'Alexander Thompson',
    type: 'Spotter',
    status: 'Active',
    startingPoint: 'Not Fixed',
    location: '4221 Curtis Ave, Baltimore, MD 21226',
    storageLot: 'Curtis Ave Storage Lot',
    zone: 'Balt CO',
    market: 'Maryland',
    shift: 'Day',
    shiftGoal: { current: 15, total: 20 }
  },
  {
    id: 'spotter-002',
    vin: 'SPOT002345678901',
    make: 'Honda',
    model: 'Civic',
    year: 2020,
    driver: 'Harper White',
    type: 'Spotter',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '135 Birch Way, Anytown',
    storageLot: 'Lot B, 101 Pine Ave, Anytown',
    zone: 'South',
    market: 'Regional',
    shift: 'Night',
    shiftGoal: { current: 5, total: 8 }
  },
  {
    id: 'spotter-003',
    vin: 'SPOT003456789012',
    make: 'Nissan',
    model: 'Altima',
    year: 2022,
    driver: 'Mason Clark',
    type: 'Spotter',
    status: 'Active',
    startingPoint: 'Not Fixed',
    location: '468 Spruce St, Anytown',
    storageLot: 'Lot C, 789 Birch St, Anytown',
    zone: 'East',
    market: 'Local',
    shift: 'Day',
    shiftGoal: { current: 9, total: 12 }
  },
  {
    id: 'spotter-004',
    vin: 'SPOT004567890123',
    make: 'Toyota',
    model: 'Corolla',
    year: 2021,
    driver: 'Evelyn Lewis',
    type: 'Spotter',
    status: 'Maintenance',
    maintenanceStatus: 'Tire Rotation',
    startingPoint: 'Fixed',
    location: '579 Walnut Ave, Anytown',
    storageLot: 'Lot A, 456 Maple Ave, Anytown',
    zone: 'North',
    market: 'Local',
    shift: 'Night',
    shiftGoal: { current: 3, total: 10 }
  },
  {
    id: 'spotter-005',
    vin: 'SPOT005678901234',
    make: 'Honda',
    model: 'Accord',
    year: 2020,
    driver: 'Logan Walker',
    type: 'Spotter',
    status: 'Active',
    startingPoint: 'Not Fixed',
    location: '680 Oak Blvd, Anytown',
    storageLot: 'Lot B, 101 Pine Ave, Anytown',
    zone: 'South',
    market: 'Regional',
    shift: 'Day',
    shiftGoal: { current: 6, total: 10 }
  },
  {
    id: 'spotter-006',
    vin: 'SPOT006789012345',
    make: 'Nissan',
    model: 'Sentra',
    year: 2023,
    driver: 'Abigail Hall',
    type: 'Spotter',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '791 Hickory Rd, Anytown',
    storageLot: 'Lot C, 789 Birch St, Anytown',
    zone: 'East',
    market: 'Local',
    shift: 'Night',
    shiftGoal: { current: 4, total: 8 }
  },
  {
    id: 'spotter-007',
    vin: 'SPOT007890123456',
    make: 'Toyota',
    model: 'Prius',
    year: 2022,
    driver: 'Caleb Young',
    type: 'Spotter',
    status: 'Inactive',
    startingPoint: 'Not Fixed',
    location: '802 Poplar Ln, Anytown',
    storageLot: 'Lot A, 456 Maple Ave, Anytown',
    zone: 'North',
    market: 'Local',
    shift: 'Day',
    shiftGoal: { current: 1, total: 10 }
  },
  {
    id: 'spotter-008',
    vin: 'SPOT008901234567',
    make: 'Honda',
    model: 'Fit',
    year: 2021,
    driver: 'Grace King',
    type: 'Spotter',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '913 Ash St, Anytown',
    storageLot: 'Lot B, 101 Pine Ave, Anytown',
    zone: 'South',
    market: 'Regional',
    shift: 'Night',
    shiftGoal: { current: 8, total: 12 }
  },

  // Rollbacks (12 total) - Flatbed tow trucks with sliding bed
  {
    id: 'rollback-001',
    vin: 'ROLL001234567890',
    make: 'Ford',
    model: 'F-650 Rollback',
    year: 2023,
    driver: 'Henry Wright',
    type: 'Rollback',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '4221 Curtis Ave, Baltimore, MD 21226',
    storageLot: 'Curtis Ave Storage Lot',
    zone: 'Balt CO',
    market: 'Maryland',
    shift: 'Day',
    shiftGoal: { current: 6, total: 8 }
  },
  {
    id: 'rollback-002',
    vin: 'ROLL002345678901',
    make: 'Chevrolet',
    model: 'Kodiak',
    year: 2021,
    driver: 'Victoria Lopez',
    type: 'Rollback',
    status: 'Active',
    startingPoint: 'Not Fixed',
    location: '235 Sycamore Way, Anytown',
    storageLot: 'Lot A, 456 Maple Ave, Anytown',
    zone: 'North',
    market: 'Local',
    shift: 'Night',
    shiftGoal: { current: 7, total: 10 }
  },
  {
    id: 'rollback-003',
    vin: 'ROLL003456789012',
    make: 'Ford',
    model: 'F-750',
    year: 2022,
    driver: 'Jackson Hill',
    type: 'Rollback',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '346 Magnolia Blvd, Anytown',
    storageLot: 'Lot B, 101 Pine Ave, Anytown',
    zone: 'South',
    market: 'Regional',
    shift: 'Day',
    shiftGoal: { current: 6, total: 10 }
  },
  {
    id: 'rollback-004',
    vin: 'ROLL004567890123',
    make: 'Chevrolet',
    model: 'Kodiak C7500',
    year: 2020,
    driver: 'Penelope Scott',
    type: 'Rollback',
    status: 'Maintenance',
    maintenanceStatus: 'Hydraulic Service',
    startingPoint: 'Not Fixed',
    location: '457 Chestnut Rd, Anytown',
    storageLot: 'Lot C, 789 Birch St, Anytown',
    zone: 'East',
    market: 'Local',
    shift: 'Night',
    shiftGoal: { current: 2, total: 8 }
  },
  {
    id: 'rollback-005',
    vin: 'ROLL005678901234',
    make: 'Ford',
    model: 'F-650',
    year: 2023,
    driver: 'Sebastian Green',
    type: 'Rollback',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '568 Locust St, Anytown',
    storageLot: 'Lot A, 456 Maple Ave, Anytown',
    zone: 'North',
    market: 'Local',
    shift: 'Day',
    shiftGoal: { current: 9, total: 12 }
  },
  {
    id: 'rollback-006',
    vin: 'ROLL006789012345',
    make: 'Chevrolet',
    model: 'Kodiak',
    year: 2021,
    driver: 'Layla Adams',
    type: 'Rollback',
    status: 'Active',
    startingPoint: 'Not Fixed',
    location: '679 Cherry Ln, Anytown',
    storageLot: 'Lot B, 101 Pine Ave, Anytown',
    zone: 'South',
    market: 'Regional',
    shift: 'Night',
    shiftGoal: { current: 4, total: 10 }
  },
  {
    id: 'rollback-007',
    vin: 'ROLL007890123456',
    make: 'Ford',
    model: 'F-750',
    year: 2022,
    driver: 'Gabriel Nelson',
    type: 'Rollback',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '780 Willow Dr, Anytown',
    storageLot: 'Lot C, 789 Birch St, Anytown',
    zone: 'East',
    market: 'Local',
    shift: 'Day',
    shiftGoal: { current: 8, total: 12 }
  },
  {
    id: 'rollback-008',
    vin: 'ROLL008901234567',
    make: 'Chevrolet',
    model: 'Kodiak C7500',
    year: 2020,
    driver: 'Zoe Carter',
    type: 'Rollback',
    status: 'Inactive',
    startingPoint: 'Not Fixed',
    location: '891 Birch Way, Anytown',
    storageLot: 'Lot A, 456 Maple Ave, Anytown',
    zone: 'North',
    market: 'Local',
    shift: 'Night',
    shiftGoal: { current: 1, total: 8 }
  },
  {
    id: 'rollback-009',
    vin: 'ROLL009012345678',
    make: 'Ford',
    model: 'F-650',
    year: 2023,
    driver: 'Carter Mitchell',
    type: 'Rollback',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '902 Spruce St, Anytown',
    storageLot: 'Lot B, 101 Pine Ave, Anytown',
    zone: 'South',
    market: 'Regional',
    shift: 'Day',
    shiftGoal: { current: 6, total: 10 }
  },
  {
    id: 'rollback-010',
    vin: 'ROLL010123456789',
    make: 'Chevrolet',
    model: 'Kodiak',
    year: 2021,
    driver: 'Chloe Perez',
    type: 'Rollback',
    status: 'Active',
    startingPoint: 'Not Fixed',
    location: '013 Walnut Ave, Anytown',
    storageLot: 'Lot C, 789 Birch St, Anytown',
    zone: 'East',
    market: 'Local',
    shift: 'Night',
    shiftGoal: { current: 5, total: 10 }
  },
  {
    id: 'rollback-011',
    vin: 'ROLL011234567890',
    make: 'Ford',
    model: 'F-750',
    year: 2022,
    driver: 'Owen Roberts',
    type: 'Rollback',
    status: 'Active',
    startingPoint: 'Fixed',
    location: '124 Oak Blvd, Anytown',
    storageLot: 'Lot A, 456 Maple Ave, Anytown',
    zone: 'North',
    market: 'Local',
    shift: 'Day',
    shiftGoal: { current: 11, total: 12 }
  },
  {
    id: 'rollback-012',
    vin: 'ROLL012345678901',
    make: 'Chevrolet',
    model: 'Kodiak C7500',
    year: 2020,
    driver: 'Nora Turner',
    type: 'Rollback',
    status: 'Maintenance',
    maintenanceStatus: 'Engine Diagnostic',
    startingPoint: 'Not Fixed',
    location: '235 Hickory Rd, Anytown',
    storageLot: 'Lot B, 101 Pine Ave, Anytown',
    zone: 'South',
    market: 'Regional',
    shift: 'Night',
    shiftGoal: { current: 3, total: 8 }
  }
];

// Helper function to get vehicles by type
export function getVehiclesByType(vehicles: FleetVehicle[], type: string): FleetVehicle[] {
  return vehicles.filter(vehicle => vehicle.type === type);
}

// Helper function to get unique values for filters
export function getUniqueMarkets(vehicles: FleetVehicle[]): string[] {
  return [...new Set(vehicles.map(v => v.market))].sort();
}

export function getUniqueZones(vehicles: FleetVehicle[]): string[] {
  return [...new Set(vehicles.map(v => v.zone))].sort();
}

export function getUniqueDrivers(vehicles: FleetVehicle[]): string[] {
  return [...new Set(vehicles.map(v => v.driver).filter(Boolean))].sort();
}

export function getUniqueMaintenanceStatuses(vehicles: FleetVehicle[]): string[] {
  return [...new Set(vehicles.map(v => v.maintenanceStatus).filter(Boolean))].sort();
}
